#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  6 17:00:47 2020

@author: aman
"""

# ['Bird', 'Ground Animal', 'Curb', 'Fence', 'Guard Rail', 'Barrier', 
# 'Wall', 'Bike Lane', 'Crosswalk - Plain', 'Curb Cut', 'Parking', 
# 'Pedestrian Area', 'Rail Track', 'Road', 'Service Lane', 'Sidewalk', 
# 'Bridge', 'Building', 'Tunnel', 'Person', 'Bicyclist', 'Motorcyclist', 
# 'Other Rider', 'Lane Marking - Crosswalk', 'Lane Marking - General', 
# 'Mountain', 'Sand', 'Sky', 'Snow', 'Terrain', 'Vegetation', 'Water', 
# 'Banner', 'Bench', 'Bike Rack', 'Billboard', 'Catch Basin', 'CCTV Camera', 
# 'Fire Hydrant', 'Junction Box', 'Mailbox', 'Manhole', 'Phone Booth', 'Pothole', 
# 'Street Light', 'Pole', 'Traffic Sign Frame', 'Utility Pole', 'Traffic Light', 
# 'Traffic Sign (Back)', 'Traffic Sign (Front)', 'Trash Can', 'Bicycle', 'Boat', 
# 'Bus', 'Car', 'Caravan', 'Motorcycle', 'On Rails', 'Other Vehicle', 'Trailer', 
# 'Truck', 'Wheeled Slow', 'Car Mount', 'Ego Vehicle']

# Label Showing -> Correct Object
# Pothole -> Traffic Light
# Traffic Sign (Front) -> Car
# Pole -> Traffic Sign (Front) ~
# Mailbox -> Pole
# Tunnel -> Person
# 

# +5?